### ISSUE TITLE
org.apache.hadoop.hdfs.server.common.IncorrectVersionException

### ISSUE THREAD

**Issue by Vzzarr** [big-data-europe/docker-hadoop-spark-workbench#46]
Thanks for the reply to the previous [issue](https://github.com/big-data-europe/docker-hadoop-spark-workbench/issues/38)

I tried to execute the new [setup](https://github.com/big-data-europe/docker-hadoop-spark-workbench/tree/master/swarm) as you suggested me in the previous issue; according to the README.md, after executing `make hadoop` I'm facing with this problem:

after the command `sudo docker service ls` I notice that hadoop_datanode doesn't start, so investigating with `sudo docker logs -f hadoop_datanode.yrqg6y0x6i9r6fzumsmas6w2d.6gmr55bf2tc68cahnyjuu5xkw` I found this exception:
`org.apache.hadoop.hdfs.server.common.IncorrectVersionException: Unexpected version of storage directory /hadoop/dfs/data. Reported: -57. Expecting = -56.`

Is there anything wrong that I could have done? Or there is any incompatibility between the docker containers?

I am waiting for a kind reply, ask me if you need for more info from the stack-trace

**Comment by earthquakesan** [comment]
Hi @Vzzarr !

Incompatible versions of HDFS means that you have started HDFS previously with different version. Now, you are trying to start HDFS with superior version and it fails. I.e. it happens when you do:
1. start docker-compose with Hadoop 1.0.0 (for example)
2. change docker-compose to Hadoop 2.7.4
Here is the point: the volumes created on step 1 will remain on your machine. Thus:
3. IncorrectVersionException

To avoid it simply wipe the data folder (if you are using the local disk mount) or remove corresponding docker volumes.

**Comment by Vzzarr** [comment]
OK thanks for your answer, indeed I removed the images using "different approaches", but I think that `docker rmi bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8` worked for me. After that I re-pulled the image from your docker-hub and the issue disappeared.
