### ISSUE TITLE
Hue docker image not availahle

### ISSUE THREAD

**Issue by sahil-sharma** [big-data-europe/docker-hadoop-spark-workbench#5]
Greetings,

I tried to run <docker-compose up -d> and got an ERROR (hue image not found) and one another as:
Unsupported config option for hue service: 'container_name'
Might be because of non-availability of hue docker image.
Can you please redirect me from where I can pull hue image or if I get hue's official image then what corresponding changes do I need to do in the code to run the set-up?
Kindly suggest.
Thanks.

**Comment by DarkBlaez** [comment]
Make sure you execute the buildall.sh script. This script may fail with an error with hue image not being found. If that's the case go in to the huebuildenv folder, execute the build.sh script to build the image, then go back and resume the original script. Also note that the ant image build might fail since the ant version that is specified is 1.9.6. However, at the location specified that version is no longer at the file location specified for apache. So change the line ENV ANT_VERSION 1.9.6 to 1.9.7

**Comment by earthquakesan** [comment]
@sahil-sharma @DarkBlaez 
Sorry for late answer, all the images are now on the Docker hub, you don't need to build anything anymore. As you can see "master" branch does not include any Dockerfiles now. I will close the issue.
