### ISSUE TITLE
Problem while running 'docker-compose up' command

### ISSUE THREAD

**Issue by punit-naik** [big-data-europe/docker-hadoop-spark-workbench#7]
I was trying this repository and when I ran 'docker-compose up' command, it got stuck at:

`datanode1      | 16/06/09 11:12:49 WARN datanode.DataNode: Problem connecting to server: namenode:8020
datanode2      | 16/06/09 11:12:52 WARN datanode.DataNode: Problem connecting to server: namenode:8020
`
Can anyone help?

**Comment by earthquakesan** [comment]
Hi @punit-naik!

This happens because docker-compose starts all the services together. Basically, datanode1/2 started before namenode. We are working on providing a way to ensure the starting order of the services. Right now, you can just restart datanode as follows (depends on which one is failing):
docker restart datanode1
docker restart datanode2

**Comment by punit-naik** [comment]
Thanks a lot @earthquakesan ! :+1:
